import { ObjectId } from "mongodb";


export interface User {
    _id?:ObjectId,
    username: string,
    password: string
}


export interface Account {
    _id?:ObjectId,
    username:string,
    profielfoto?:string,
    favoriet:Favoriet[],
    blacklist:Blacklist[]
}

export interface Blacklist {
    naam:string,
    reden:string,
    rarity:string,
    img:string
}

export interface Favoriet {
    naam:string,
    notitie:string,
    item1:string,
    item2:string,
    wins:number,
    loses:number
}

//generated by https://app.quicktype.io/
export interface Fortnite {
    id:               string;
    name:             string;
    description:      string;
    type:             Rarity;
    rarity:           Rarity;
    series:           null;
    set:              null;
    introduction:     Introduction;
    images:           Images;
    variants:         null;
    searchTags:       null;
    gameplayTags:     string[];
    metaTags:         null;
    showcaseVideo:    string;
    dynamicPakId:     null;
    displayAssetPath: null;
    definitionPath:   string;
    path:             string;
    added:            Date;
    shopHistory:      Date[];
}

export interface Images {
    smallIcon: string;
    icon:      string;
    featured:  string;
    other:     null;
}

export interface Introduction {
    chapter:      string;
    season:       string;
    text:         string;
    backendValue: number;
}

export interface Rarity {
    value:        string;
    displayValue: string;
    backendValue: string;
}